<a href="https://colab.research.google.com/github/SushanthKumble/DATASCIENCE/blob/main/example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PERFORM NUMERICAL ANALYSIS AND DATA MANIPULATION USING THE NUMPY LIBRARY

In [ ]:
import pandas as pd
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
#printing the second element
print("the element in the second index is ")
print(arr[2])
print("MANIPULATIONG THE ARRAY")
arr[2]=7
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
the element in the second index is 
3
MANIPULATIONG THE ARRAY
[ 1  2  7  4  5  6  7  8  9 10]


TWO DIMENSIONAL ARRAY CREATION ACCESSING AND MANIPULATING

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
#accessing the array elements
print("the element in the first row second col is ")
print(arr[0][2])
#manipulating the array
arr[0][2]=7
print(arr)
#returning he shape
arr.shape[0]



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the element in the first row second col is 
3
[[ 1  2  7  4  5]
 [ 6  7  8  9 10]]


2

CREATING AN ARRAY USING THE STRING 

In [ ]:
import numpy as np
arr=np.array({'india','china','japan'})
print(arr)


{'india', 'japan', 'china'}


USING THE ARRANGE() AND INSPACE FUNCTION TO EVEN SPACE VALUES IN SPECIFIED INTERVALS

In [ ]:
import numpy as np
#to get the values with difference 2 each(even number upto20)
x=np.arange(0,20,2)
print(x)
print("\n")
#using linespae
y=np.linspace(0,2,10)
print(y)

[ 0  2  4  6  8 10 12 14 16 18]


[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


CREATE AN ARRAY OF RANDOM VALUES BETWEEN 0 AND1 IN A GIVEN SHAPE

In [ ]:
import numpy as np
x=np.random.rand(10)
print(x)
print("\n")
y=np.random.rand(3,4)
print(y)

[0.91380338 0.25226864 0.59592322 0.09487354 0.86716062 0.94730329
 0.50031668 0.62949139 0.5985675  0.04411232]


[[0.94420848 0.20542384 0.12158954 0.53624757]
 [0.70868816 0.30572488 0.97010485 0.00457335]
 [0.71157722 0.41582914 0.08407222 0.1880065 ]]


CREATE AN ARRAY OF CONSTANT VALUES IN A  GIVEN SHAPE

In [ ]:
import numpy as np
c = np.full([3, 3], 10.1)
print(c)

[[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


REPEAT EACH ELEMENT OF AN ARRAY BY A SPECIFIED NUMBER OF TIMES USING REPEAT()

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.repeat(arr,3))
#using tile function
print("\n")
print(np.tile(arr,2))

[ 1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7  8  8  8
  9  9  9 10 10 10]


[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


CREATE AN IDENTITY MATRIX USING EYE() AND IDENTITY() FUNCTION

In [ ]:
import numpy as np
idm=np.eye(3)
print(idm)
print("\n")
#using the identity function 
idm2=np.identity(4)
print(idm2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


CREATE A 5*5 2D ARRAY FOR RANDOM NUMBERS BETWEEN 0 AND 1 AND FIND THE SUM ALONG THE COLUMN AND ROW

In [ ]:
import numpy as np
arr=np.random.rand(5,5)
print(arr)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
#finding the sum along the col
print("the sum along the column is :\n")
print(np.sum(arr2,axis=1))
print("the sum along the row is :\n")
print(np.sum(arr2,axis=0))
#determning the mean,median,standard deviation and variance
print("the mean of arr2 is:",np.mean(arr2))
print("the median of arr2 is:",np.median(arr2))
print("the standard deviation of arr2 is:",np.std(arr2))
print("the variance of arr2 is:",np.var(arr2)).

[[0.83746453 0.45036733 0.63890591 0.08229688 0.1837402 ]
 [0.71174659 0.822451   0.00816313 0.71312092 0.32865919]
 [0.93961057 0.84304866 0.04067079 0.81445072 0.00217593]
 [0.38213107 0.68824032 0.75131221 0.5503964  0.38888529]
 [0.17558567 0.11669019 0.0430913  0.57777588 0.80406549]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the sum along the column is :

[15 40]
the sum along the row is :

[ 7  9 11 13 15]
the mean of arr2 is: 5.5
the median of arr2 is: 5.5
the standard deviation of arr2 is: 2.8722813232690143
the variance of arr2 is: 8.25


APPENDING AN ELEMENT TO THE ARRAY

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr=np.append(arr,8)
print("array after appending:",arr)
arr=np.append(arr,[11,13,12])
print("array after appending:",arr)
print(np.sort(arr,axis=0))


[ 1  2  3  4  5  6  7  8  9 10]
array after appending: [ 1  2  3  4  5  6  7  8  9 10  8]
array after appending: [ 1  2  3  4  5  6  7  8  9 10  8 11 13 12]
[ 1  2  3  4  5  6  7  8  8  9 10 11 12 13]


DELETE MULTIPLE ELEMENT IN AN ARRAY

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr=np.delete(arr,[1,2])
print("after deletion the array looks like",arr)

[ 1  2  3  4  5  6  7  8  9 10]
after deletion the array looks like [ 1  4  5  6  7  8  9 10]


CONCATENATE ELEMENTS FROM 2 ARRAYS(ROW WISE AND COLUN WISE)

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.array([11,12,13])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
